/** Dossier UI's source of truth. CSS is generated by scripts/generate.mjs. */
export const colors = {
  paper: '#f2f0e9',
  paperMuted: '#e8e5dc',
  ink: '#242321',
  inkSoft: '#4c4943',
  inkMuted: '#6c6860',
  rule: '#403e39',
  ruleLight: '#c8c4b9',
  accentRed: '#a13c35',
  accentBlue: '#355d91',
  accentGreen: '#3d714f',
  accentAmber: '#7d5d20',
} as const;

export const darkColors = {
  paper: '#161614',
  paperMuted: '#22221e',
  ink: '#e8e4d9',
  inkSoft: '#c2beb3',
  inkMuted: '#a49f95',
  rule: '#8f8b83',
  ruleLight: '#46443e',
  accentRed: '#e69286',
  accentBlue: '#96b7e2',
  accentGreen: '#96bd9e',
  accentAmber: '#d1b46e',
} as const;

export const typography = {
  fontMono: '"IBM Plex Mono", "JetBrains Mono", "Roboto Mono", "SFMono-Regular", Consolas, "Liberation Mono", monospace',
  text2xs: '0.625rem',
  textXs: '0.6875rem',
  textSm: '0.75rem',
  textMd: '0.875rem',
  textLg: '1rem',
  textXl: '1.25rem',
  text2xl: '1.625rem',
  text3xl: '2rem',
} as const;

export const spacing = { 0: '0', 1: '4px', 2: '8px', 3: '12px', 4: '16px', 5: '20px', 6: '24px', 8: '32px', 10: '40px', 12: '48px' } as const;
export const radii = { xs: '1px', sm: '2px', md: '3px' } as const;
export const motion = { fast: '120ms ease', normal: '180ms ease' } as const;
export const zIndex = { sticky: '10', dropdown: '20', overlay: '40', toast: '60', tooltip: '70' } as const;
export const density = {
  compact: { controlHeight: '28px', controlPadding: '6px', rowPadding: '6px', densityGap: '8px' },
  default: { controlHeight: '34px', controlPadding: '10px', rowPadding: '10px', densityGap: '12px' },
  comfortable: { controlHeight: '42px', controlPadding: '14px', rowPadding: '14px', densityGap: '16px' },
} as const;

export const tokens = { colors, darkColors, typography, spacing, radii, motion, zIndex, density } as const;
