import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Button, Status, Tag, Dialog, CodeBlock, DataTable, Metric, MetricGroup, Rule, Field, Input, Callout, useToast } from '@dossier-ui/react';
import { Icon } from '@dossier-ui/icons';
import { colors, spacing } from '@dossier-ui/tokens';
import { allPages, catalog, componentGroups, generalPages, type ComponentEntry } from './catalog';
import { ComponentDemo, Dashboard, LayoutExample, TypographyExample, SampleChart, events, eventColumns } from './examples';

type Theme = 'paper' | 'dark';
type Density = 'compact' | 'default' | 'comfortable';
function stored(key: string, fallback: string) { try { return localStorage.getItem(key) || fallback; } catch { return fallback; } }
function getRoute() { return window.location.hash.replace(/^#\/?/, '').split('?')[0] || 'overview'; }
function navigate(id: string) { window.location.hash = `/${id}`; }

function CopyButton({ text, label = 'Copy' }: { text: string; label?: string }) {
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();
  const timer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);
  useEffect(()=>()=>clearTimeout(timer.current),[]);
  return <button className="copy-control" aria-label={copied ? 'Copied to clipboard' : label} onClick={async()=>{
    try { await navigator.clipboard.writeText(text); setCopied(true); clearTimeout(timer.current); timer.current=setTimeout(()=>setCopied(false),2000); }
    catch { toast({title:'Clipboard unavailable',description:'Select the command and copy it manually.',tone:'warning'}); }
  }}><Icon name={copied ? 'check' : 'copy'} size={14} /><span>{copied ? 'Copied' : label}</span></button>;
}
function SectionTitle({ index, children, right, id }: { index: string; children: ReactNode; right?: ReactNode; id?: string }) {
  return <div className="doc-section-title" id={id}><h2><span>{index}</span>{children}</h2>{right}</div>;
}
function MiniSpecimen({ kind }: {kind:string}) {
  if(kind==='inputs') return <div className="mini-inputs"><div className="mini-label">ENVIRONMENT</div><div className="mini-field">relay-production<span>↵</span></div><div className="mini-buttons"><span>DEPLOY ↗</span><span>REVIEW</span></div></div>;
  if(kind==='data') return <div className="mini-table"><div><span>PROVIDER</span><span>STATUS</span></div><div><span>SINCH</span><span className="green-text">● DELIVERED</span></div><div><span>AMAZON SES</span><span className="green-text">● DELIVERED</span></div><div><span>META</span><span className="red-text">● FAILED</span></div></div>;
  if(kind==='document') return <div className="mini-document"><small>RELAY / COMMUNICATIONS</small><strong>SYSTEM REPORT</strong><div className="mini-document-rule"/><div><span>ENV PROD</span><span>REV 17</span></div><p><b>03</b> PROVIDER HEALTH</p></div>;
  if(kind==='navigation') return <div className="mini-navigation"><div><b>OVERVIEW</b><span>EVENTS</span><span>AUDIT</span></div><p>01 <b>Overview</b></p><p>02 Events <span>128</span></p><p>03 Providers</p></div>;
  if(kind==='feedback') return <div className="mini-feedback"><p><span>i</span><b>SYSTEM NOTICE</b></p><span>Configuration saved successfully.</span><div><span className="green-text">[ SUCCESS ]</span><span>REV 18</span></div></div>;
  return <div className="mini-code"><p><span>01</span><b>13:40:22</b> EVENT_ACCEPTED</p><p><span>02</span><b>13:40:22</b> POLICY_MATCH</p><p><span>03</span><b>13:40:22</b> PROVIDER_SENT</p><p><span>04</span><b>13:40:22</b><i> DELIVERED</i></p></div>;
}
const categories = [
  {name:'Inputs',kind:'inputs',description:'Precise controls. Deliberate actions.',items:'Button · Input · Select · Checkbox',target:'button'},
  {name:'Data display',kind:'data',description:'Dense information, clearly expressed.',items:'DataTable · Metric · Status · Tag',target:'data-table'},
  {name:'Document',kind:'document',description:'A structure for every layer of context.',items:'Header · Section · Rule · Figure',target:'document-header'},
  {name:'Navigation',kind:'navigation',description:'An index for your application.',items:'Tabs · Sidebar · Breadcrumb',target:'tabs'},
  {name:'Feedback',kind:'feedback',description:'System state, without the noise.',items:'Dialog · Toast · Tooltip · Callout',target:'dialog'},
  {name:'Technical',kind:'technical',description:'Tools for looking under the hood.',items:'CodeBlock · LogViewer · JSON',target:'code-block'},
];

function Overview() {
  return <>
    <div className="hero" id="introduction"><div className="eyebrow"><span className="small-cross">+</span> A VISUAL LANGUAGE FOR TECHNICAL SYSTEMS</div><div className="hero-heading"><h1>Structure.<br />Signal. <span>Substance.</span></h1><div className="document-stamp"><span>DOCUMENT</span><strong>001</strong><span>FRAMEWORK REFERENCE</span><div>PAPER EDITION / 2026</div></div></div><p className="hero-description">A React component framework for interfaces that mean business.<br className="desktop-break" /> Built on typography, rules, and the clarity of a well-made document.</p><div className="hero-actions"><a className="solid-link" href="#/installation">Get started <Icon name="arrow-up-right" size={16} /></a><a className="text-link" href="#/components">Explore components <Icon name="arrow-right" size={15} /></a></div><div className="install-command"><span className="prompt-symbol">$</span><code>pnpm add @dossier-ui/react</code><CopyButton text="pnpm add @dossier-ui/react" label="Copy command" /></div><div className="install-note">Local packages are ready to build. Registry publishing is a separate step.</div></div>
    <div className="framework-facts"><div><b>{catalog.length}</b><span>COMPONENT FAMILIES</span></div><div><b>02</b><span>PAPER & DARK THEMES</span></div><div><b>03</b><span>DENSITY MODES</span></div><div><span className="fact-symbol">Aa</span><span>MONOSPACE BY DESIGN</span></div></div>
    <SectionTitle index="01" id="component-index" right={<a href="#/components">View all components <Icon name="arrow-up-right" size={13} /></a>}>Component index</SectionTitle>
    <div className="category-grid">{categories.map((c,i)=><a href={`#/${c.target}`} className="category-card" key={c.kind}><div className="category-meta"><span>0{i+1} / {c.name.toUpperCase()}</span><Icon name="arrow-up-right" size={15}/></div><div className="category-specimen" aria-hidden="true"><MiniSpecimen kind={c.kind}/></div><h3>{c.name}</h3><p>{c.description}</p><div className="category-items">{c.items}</div></a>)}</div>
    <SectionTitle index="02" id="in-context" right={<a href="#/dashboard">Open example <Icon name="arrow-up-right" size={13}/></a>}>The system, in context</SectionTitle>
    <p className="section-intro">One coherent language. From the first metric to the last event.</p><div className="context-specimen"><div className="context-heading"><div><span>RELAY / EVENT INFRASTRUCTURE</span><h3>DELIVERY CONTROL PLANE</h3></div><Status tone="success">Operational</Status></div><div className="context-metadata"><span>ENV <b>PROD</b></span><span>REGION <b>AP-SOUTH-1</b></span><span>REV <b>17</b></span><span>ILLUSTRATIVE DATA</span></div><MetricGroup><Metric label="EVENTS PROCESSED" value="12,482" trend="+4.6%"/><Metric label="DELIVERY RATE" value="98.7%" tone="success"/><Metric label="P95 LATENCY" value="420ms"/></MetricGroup><div className="chart-kicker">FIGURE 01 <b>EVENT THROUGHPUT</b><span>LAST 24 HOURS</span></div><SampleChart small/><DataTable columns={eventColumns} rows={events.slice(0,3)} density="compact" numbered /></div>
    <div className="principle-strip" id="design-philosophy"><span className="bracket-mark">[ D ]</span><div><h3>Less decoration. More information.</h3><p>No shadows. No gradients. No unnecessary curves.<br/>Just the structure your data deserves.</p></div><a href="#/principles" className="text-link">Read the principles <Icon name="arrow-right" size={15}/></a></div>
  </>;
}

function Preview({ entry }: {entry:ComponentEntry}) {
  const [tab,setTab] = useState<'preview'|'code'>('preview');
  const [key,setKey] = useState(0);
  return <div className="component-preview"><div className="preview-toolbar"><div role="tablist" aria-label="Example view"><button id="preview-tab" role="tab" aria-selected={tab==='preview'} aria-controls="component-preview-panel" tabIndex={tab==='preview'?0:-1} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){setTab('code');document.getElementById('code-tab')?.focus();}}} onClick={()=>setTab('preview')}><Icon name="grid" size={13}/>Preview</button><button id="code-tab" role="tab" aria-selected={tab==='code'} aria-controls="component-code-panel" tabIndex={tab==='code'?0:-1} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){setTab('preview');document.getElementById('preview-tab')?.focus();}}} onClick={()=>setTab('code')}><Icon name="code" size={14}/>Code</button></div><button className="reset-demo" onClick={()=>setKey(k=>k+1)}>Reset example ↻</button></div><div id="component-preview-panel" role="tabpanel" aria-labelledby="preview-tab" hidden={tab!=='preview'} className="preview-canvas"><ComponentDemo id={entry.id} key={key}/></div><div id="component-code-panel" role="tabpanel" aria-labelledby="code-tab" hidden={tab!=='code'}><CodeBlock language="tsx" filename={`${entry.name}.tsx`}>{entry.code}</CodeBlock></div><div className="preview-caption"><span>LIVE COMPONENT / INTERACTIVE</span><span>REACT + TYPESCRIPT</span></div></div>;
}
function ComponentPage({entry}:{entry:ComponentEntry}) {
  const index = catalog.indexOf(entry);
  return <><PageHeading eyebrow={`${entry.group.toUpperCase()} / COMPONENT REFERENCE`} title={entry.name} description={entry.description}/><div className="component-badges"><Tag>React</Tag><Tag>TypeScript</Tag><Tag>CSS variables</Tag><span>IMPORT FROM @DOSSIER-UI/REACT</span></div><SectionTitle index="01" id="usage">Usage</SectionTitle><Preview entry={entry}/><SectionTitle index="02" id="import">Import</SectionTitle><CodeBlock language="tsx">{`import { ${entry.name === 'Loading' ? 'TableSkeleton, InlineLoader' : entry.name} } from "@dossier-ui/react";\nimport "@dossier-ui/react/styles.css";`}</CodeBlock><SectionTitle index="03" id="api">API reference</SectionTitle><p className="section-intro">Native HTML attributes are supported where applicable. Refs are forwarded by form controls.</p><div className="api-table-wrap"><table className="api-table"><thead><tr><th>PROP</th><th>TYPE</th><th>DEFAULT</th></tr></thead><tbody>{[...entry.props,['className','string','—'],['children','ReactNode','—']].map(([name,type,def])=><tr key={name}><td><code>{name}</code></td><td><code>{type}</code></td><td>{def}</td></tr>)}</tbody></table></div><SectionTitle index="04" id="accessibility">Accessibility</SectionTitle><Callout title="BUILT FOR KEYBOARD USERS" tone="info">Use descriptive labels, preserve the visible focus outline, and provide text alongside semantic colors. Try the live example using Tab and your keyboard.</Callout><div className="page-pagination">{index>0?<a href={`#/${catalog[index-1].id}`}><span>← PREVIOUS</span><b>{catalog[index-1].name}</b></a>:<span/>}{index<catalog.length-1&&<a href={`#/${catalog[index+1].id}`}><span>NEXT →</span><b>{catalog[index+1].name}</b></a>}</div></>;
}
function PageHeading({eyebrow,title,description}:{eyebrow:string;title:string;description:string}) {return <div className="page-heading"><div className="eyebrow"><span className="small-cross">+</span>{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>;}
function ComponentIndex() {
  const [filter,setFilter] = useState('');
  return <><PageHeading eyebrow="REFERENCE / COMPLETE INDEX" title="Every part has a purpose." description="Explore the building blocks of a technical interface. Live previews, working examples, and the details that matter."/><div className="index-filter"><Icon name="search" size={16}/><input aria-label="Filter components" placeholder="Find a component…" value={filter} onChange={e=>setFilter(e.target.value)}/><span>{catalog.filter(c=>(c.name+c.description).toLowerCase().includes(filter.toLowerCase())).length} RESULTS</span></div>{componentGroups.map((group,i)=>{const components=catalog.filter(c=>c.group===group&&(c.name+c.description).toLowerCase().includes(filter.toLowerCase()));return components.length?<section key={group}><SectionTitle index={`0${i+1}`}>{group}</SectionTitle><div className="component-index-grid">{components.map(c=><a href={`#/${c.id}`} key={c.id}><h3>{c.name}<Icon name="arrow-up-right" size={14}/></h3><p>{c.description}</p></a>)}</div></section>:null;})}{!catalog.some(c=>(c.name+c.description).toLowerCase().includes(filter.toLowerCase()))&&<div className="no-results">No components match “{filter}”. <button onClick={()=>setFilter('')}>Clear search</button></div>}</>;
}
function Installation() {return <><PageHeading eyebrow="GETTING STARTED / 01" title="Start with structure." description="Dossier UI is a React library with a small CSS layer. No styling runtime, no utility framework, and no complicated setup."/><Callout tone="info" title="LOCAL DEVELOPMENT RELEASE">Version 0.1.0 is built locally in this workspace. Use the packages from the monorepo or install a packed build in another app. The package names below are reserved for your release; they are not assumed to be published.</Callout><SectionTitle index="01" id="workspace">Run this workspace</SectionTitle><CodeBlock language="bash">{'pnpm install\npnpm dev\n\n# Documentation: http://127.0.0.1:5173\npnpm dev:playground\n# Dashboard: http://127.0.0.1:5174\n\npnpm storybook\n# Storybook: http://localhost:6006'}</CodeBlock><SectionTitle index="02" id="install">Use in another app</SectionTitle><p className="section-intro">Build the packages and create a portable archive, then install that archive in your React application. React 18.3 or newer is required.</p><CodeBlock language="bash">{'# In the Dossier UI workspace\npnpm build:packages\npnpm --dir packages/react pack\n\n# In your application (adjust the path)\npnpm add /path/to/dossier-ui-react-0.1.0.tgz'}</CodeBlock><SectionTitle index="03" id="first-component">Your first component</SectionTitle><CodeBlock language="tsx" filename="App.tsx">{'import { DossierProvider, DocumentHeader, Button } from "@dossier-ui/react";\nimport "@dossier-ui/react/styles.css";\n\nexport default function App() {\n  return (\n    <DossierProvider theme="paper" density="default">\n      <DocumentHeader\n        kicker="RELAY / EVENT INFRASTRUCTURE"\n        title="SYSTEM OVERVIEW"\n      />\n      <Button variant="solid">Deploy changes</Button>\n    </DossierProvider>\n  );\n}'}</CodeBlock><SectionTitle index="04" id="theming">Make it yours</SectionTitle><p className="section-intro">Set a theme on the document or a provider. Every design token can be overridden with plain CSS.</p><CodeBlock language="css">{':root {\n  --dossier-accent-blue: #274c77;\n  --dossier-font-mono: "Your Mono Font", monospace;\n}\n\n/* Switch the whole document using: */\n/* <html data-dossier-theme="dark"> */'}</CodeBlock><a href="#/button" className="solid-link">Explore your first component <Icon name="arrow-right" size={15}/></a></>;}
function Principles() {const list=[['Data first','The interface exists to communicate information. Put numbers, labels, and the relationship between them ahead of decoration.'],['Lines instead of cards','Horizontal rules and fine borders create structure without adding visual weight. Surfaces do not need to float to be distinct.'],['A monospace identity','A shared rhythm connects labels, identifiers, logs, and metrics. Tabular numerals make comparisons immediate.'],['Dense, but readable','Support compact work without sacrificing usable touch targets, visible focus, or a clear hierarchy.'],['Color has a job','Green signals success, red signals failure, blue signals information, and amber asks for attention. Always add a text label.'],['Built to be composed','Small, predictable components form reports, consoles, and applications. CSS variables let the system adapt without losing its structure.']];return <><PageHeading eyebrow="FOUNDATIONS / DESIGN PHILOSOPHY" title="Clarity is the aesthetic." description="Research papers, engineering schematics, and archival documents share a quality: every mark means something. Dossier UI starts there."/>{list.map(([title,body],i)=><section className="principle-entry" key={title}><span>0{i+1}</span><div><h2>{title}</h2><p>{body}</p></div></section>)}<Rule weight="heavy"/><TypographyExample/></>;}
function Tokens() {return <><PageHeading eyebrow="FOUNDATIONS / DESIGN TOKENS" title="A shared vocabulary." description="Every color, space, and typographic decision starts here. A single TypeScript source generates the theme's CSS custom properties."/><SectionTitle index="01" id="palette">Color palette</SectionTitle><div className="token-grid">{Object.entries(colors).map(([name,value])=><div className="token-swatch" key={name}><div style={{background:`var(--dossier-${name.replace(/[A-Z]/g,l=>`-${l.toLowerCase()}`)})`}}/><b>{name.replace(/[A-Z]/g,l=>` ${l}`).toUpperCase()}</b><code>{value}</code><span>--dossier-{name.replace(/[A-Z]/g,l=>`-${l.toLowerCase()}`)}</span></div>)}</div><p className="token-note">Hex values show the paper theme. Swatches follow the active theme.</p><SectionTitle index="02" id="spacing">Spacing scale</SectionTitle><div className="spacing-list">{Object.entries(spacing).map(([key,value])=><div key={key}><code>--dossier-space-{key}</code><span style={{width:value}}/><b>{value}</b></div>)}</div><SectionTitle index="03" id="customization">Override any token</SectionTitle><CodeBlock language="css">{'.my-application {\n  --dossier-paper: #f7f5ef;\n  --dossier-accent-blue: #274c77;\n  --dossier-control-height: 36px;\n}'}</CodeBlock></>;}
function LayoutPage(){return <><PageHeading eyebrow="FOUNDATIONS / LAYOUT" title="Compose with precision." description="A practical set of layout primitives keeps dense interfaces aligned and responsive."/><SectionTitle index="01" id="grid">Twelve-column grid</SectionTitle><div className="preview-canvas bordered"><LayoutExample/></div><CodeBlock language="tsx">{'<Grid columns={12}>\n  <Grid.Item span={8}>Main content</Grid.Item>\n  <Grid.Item span={4}>Supporting context</Grid.Item>\n</Grid>'}</CodeBlock><SectionTitle index="02" id="density">Three levels of density</SectionTitle><p className="section-intro">Change the density control in the top bar to try each mode. Density changes control height, table padding, and spacing without shrinking the type.</p>{(['compact','default','comfortable'] as const).map(d=><div key={d} data-dossier-density={d} className="density-example"><span>{d.toUpperCase()}</span><Input aria-label={`${d} input`} placeholder="Tenant identifier"/><Button>Apply</Button></div>)}<SectionTitle index="03" id="primitives">Layout primitives</SectionTitle><div className="api-table-wrap"><table className="api-table"><tbody>{[['Container','Constrain a page to a readable maximum width.'],['Stack','Arrange content vertically with a consistent gap.'],['Inline / Cluster','Wrap related controls and labels.'],['Split','Separate primary and secondary information.'],['Grid','Create equal columns or a 12-column layout.'],['Document / Section','Structure the page as an indexed report.']].map(([name,description])=><tr key={name}><th>{name}</th><td>{description}</td></tr>)}</tbody></table></div></>;}

export function App() {
  const [route,setRoute] = useState(getRoute);
  const [theme,setTheme] = useState<Theme>(()=>stored('dossier-theme','paper')==='dark'?'dark':'paper');
  const [density,setDensity] = useState<Density>(()=>{const d=stored('dossier-density','default');return d==='compact'||d==='comfortable'?d:'default';});
  const [searchOpen,setSearchOpen] = useState(false);
  const [query,setQuery] = useState('');
  const [mobileOpen,setMobileOpen] = useState(false);
  const searchRef=useRef<HTMLInputElement>(null);
  const mainRef=useRef<HTMLElement>(null);
  useEffect(()=>{const listener=()=>{setRoute(getRoute());setMobileOpen(false);window.scrollTo({top:0});mainRef.current?.focus({preventScroll:true});};window.addEventListener('hashchange',listener);return()=>window.removeEventListener('hashchange',listener);},[]);
  useEffect(()=>{document.documentElement.dataset.dossierTheme=theme;document.documentElement.dataset.dossierDensity=density;try{localStorage.setItem('dossier-theme',theme);localStorage.setItem('dossier-density',density);}catch{/* Preferences are optional in restricted contexts. */}},[theme,density]);
  useEffect(()=>{const listener=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();setSearchOpen(s=>!s);}if(e.key==='Escape')setMobileOpen(false);};window.addEventListener('keydown',listener);return()=>window.removeEventListener('keydown',listener);},[]);
  useEffect(()=>{document.title=`${allPages.find(p=>p.id===route)?.name||'Page not found'} — Dossier UI`;},[route]);
  const current=allPages.find(p=>p.id===route);
  const component=catalog.find(c=>c.id===route);
  const results=allPages.filter(p=>(p.name+' '+p.group+' '+p.description).toLowerCase().includes(query.toLowerCase()));
  const openSearch=()=>{setQuery('');setSearchOpen(true);};
  const onThisPage=component?[['usage','Usage'],['import','Import'],['api','API reference'],['accessibility','Accessibility']]:route==='overview'?[['introduction','Introduction'],['component-index','Component index'],['in-context','In context'],['design-philosophy','Design philosophy']]:route==='installation'?[['workspace','Run locally'],['install','Installation'],['first-component','First component'],['theming','Theming']]:route==='tokens'?[['palette','Color palette'],['spacing','Spacing scale'],['customization','Customization']]:route==='layout'?[['grid','Grid'],['density','Density'],['primitives','Primitives']]:[];
  function renderPage(){if(component)return <ComponentPage entry={component}/>;switch(route){case 'overview':return <Overview/>;case 'components':return <ComponentIndex/>;case 'installation':return <Installation/>;case 'principles':return <Principles/>;case 'tokens':return <Tokens/>;case 'typography':return <><PageHeading eyebrow="FOUNDATIONS / TYPOGRAPHY" title="A measured rhythm." description="Monospace typography is the connective tissue of the system. Precise labels, legible body text, and aligned numbers."/><TypographyExample/><SectionTitle index="01">The font stack</SectionTitle><CodeBlock language="css">{'--dossier-font-mono:\n  "IBM Plex Mono", "JetBrains Mono", "Roboto Mono",\n  "SFMono-Regular", Consolas, "Liberation Mono", monospace;'}</CodeBlock><Callout title="BRING YOUR OWN FONT">Dossier UI ships a system font stack. Add an open-source monospace font or use your preferred local font by overriding the token.</Callout></>;case 'layout':return <LayoutPage/>;case 'dashboard':return <><div className="example-label"><span>EXAMPLE 01 / INTERACTIVE DASHBOARD</span><Tag>Sample data</Tag></div><Dashboard/></>;case 'changelog':return <><PageHeading eyebrow="RESOURCES / RELEASE NOTES" title="A record of changes." description="The evolution of Dossier UI, documented."/><SectionTitle index="01">Version 0.1.0</SectionTitle><p>Initial local development release.</p><ul className="release-list"><li>Paper and dark themes with three density modes.</li><li>Reusable React components and standalone CSS tokens.</li><li>Searchable documentation, interactive examples, and API references.</li><li>Sortable, selectable, paginated data tables.</li><li>Storybook, unit tests, and browser checks.</li></ul></>;default:return <><PageHeading eyebrow="REFERENCE / 404" title="Document not found." description="This page is not in the current index."/><a className="solid-link" href="#/overview">Return to overview <Icon name="arrow-right" size={15}/></a></>;}}
  return <div className="docs-app ds-root"><a className="skip-link" href="#main-content" onClick={e=>{e.preventDefault();mainRef.current?.focus();}}>Skip to content</a><header className="site-header"><button className="mobile-menu icon-control" aria-label={mobileOpen?'Close navigation':'Open navigation'} aria-expanded={mobileOpen} onClick={()=>setMobileOpen(!mobileOpen)}><Icon name={mobileOpen?'close':'menu'} size={20}/></button><a className="brand" href="#/overview" aria-label="Dossier UI home"><span className="brand-monogram">D<span>_</span></span><strong>DOSSIER<span> / UI</span></strong></a><nav className="header-nav" aria-label="Main navigation"><a className={route!=='dashboard'?'active':''} href="#/overview">Documentation</a><a className={route==='dashboard'?'active':''} href="#/dashboard">Examples <Icon name="arrow-up-right" size={12}/></a></nav><div className="header-tools"><button className="search-trigger" onClick={openSearch}><Icon name="search" size={15}/><span>Search documentation…</span><kbd>Ctrl K</kbd></button><span className="version-mark">v0.1.0</span><button className="icon-control theme-toggle" aria-label={`Switch to ${theme==='paper'?'dark':'paper'} theme`} onClick={()=>setTheme(t=>t==='paper'?'dark':'paper')}><Icon name={theme==='paper'?'moon':'sun'} size={17}/></button></div></header>
    {mobileOpen&&<button className="mobile-scrim" aria-label="Close navigation" onClick={()=>setMobileOpen(false)}/>}
    <aside className={`docs-sidebar ${mobileOpen?'is-open':''}`} aria-label="Documentation navigation"><div className="sidebar-edition"><span>REFERENCE MANUAL</span><b>VOL. 01</b></div><div className="sidebar-scroll"><div className="sidebar-group"><h2>GETTING STARTED</h2>{generalPages.filter(p=>p.group==='Getting started').map(p=><a aria-current={route===p.id?'page':undefined} key={p.id} href={`#/${p.id}`}><span>{p.name}</span>{p.id==='overview'&&<span className="nav-index">00</span>}</a>)}</div><div className="sidebar-group"><h2>FOUNDATIONS</h2>{generalPages.filter(p=>p.group==='Foundations').map(p=><a aria-current={route===p.id?'page':undefined} key={p.id} href={`#/${p.id}`}>{p.name}</a>)}</div><div className="sidebar-group"><h2>COMPONENTS <span>{catalog.length}</span></h2><a className="all-components-link" href="#/components" aria-current={route==='components'?'page':undefined}><Icon name="grid" size={13}/> All components <Icon name="arrow-up-right" size={12}/></a>{componentGroups.map(group=><div className="sidebar-subgroup" key={group}><h3>{group}</h3>{catalog.filter(c=>c.group===group).map(c=><a href={`#/${c.id}`} key={c.id} aria-current={route===c.id?'page':undefined}>{c.name}{['data-table','figure','metric-row'].includes(c.id)&&<span className="signature-dot" title="Signature component"/>}</a>)}</div>)}</div><div className="sidebar-group"><h2>RESOURCES</h2><a href="#/dashboard" aria-current={route==='dashboard'?'page':undefined}>Example dashboard <Icon name="arrow-up-right" size={12}/></a><a href="#/changelog" aria-current={route==='changelog'?'page':undefined}>Changelog</a></div></div><div className="sidebar-footer"><span className="green-dot"/>SYSTEM v0.1.0<span>REACT / TS</span></div></aside>
    <div className={`main-layout ${route==='dashboard'?'main-layout--wide':''}`}><main id="main-content" tabIndex={-1} ref={mainRef}><div className="page-topline"><nav className="page-breadcrumb" aria-label="Breadcrumb"><a href="#/overview">Docs</a><span>/</span><span>{current?.name||'Not found'}</span></nav><div className="density-control"><label htmlFor="density">DENSITY</label><select id="density" value={density} onChange={e=>setDensity(e.target.value as Density)}><option value="compact">Compact</option><option value="default">Default</option><option value="comfortable">Comfortable</option></select></div></div><div key={route}>{renderPage()}</div><footer className="page-footer"><span><b>DOSSIER UI</b> / A FRAMEWORK FOR TECHNICAL SYSTEMS</span><span>BUILT WITH INTENT. <span className="small-cross">+</span></span></footer></main>{route!=='dashboard'&&<aside className="page-toc" aria-label="On this page"><span className="toc-heading">ON THIS PAGE</span>{onThisPage.map(([id,title],i)=><button key={id} className={i===0?'toc-first':''} onClick={()=>document.getElementById(id)?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}>{title}</button>)}<div className="toc-note"><span>THE DOSSIER METHOD</span><p>Typography.<br/>Rules. Density.<br/>Structured information.</p><a href="#/principles">Our principles ↗</a></div><div className="toc-edition">DS—UI<br/>REFERENCE / 001<br/><span>EDITION 2026</span></div></aside>}</div>
    <Dialog open={searchOpen} onOpenChange={setSearchOpen} title="Search documentation" description="Find components, foundations, and examples."><div className="search-dialog"><Field label="SEARCH"><Input ref={searchRef} autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try DataTable, themes, or input…" onKeyDown={e=>{if(e.key==='Enter'&&results[0]){navigate(results[0].id);setSearchOpen(false);}}}/></Field><div className="search-results">{results.length?results.slice(0,12).map(p=><button key={p.id} onClick={()=>{navigate(p.id);setSearchOpen(false);}}><span><b>{p.name}</b><small>{p.group}</small></span><Icon name="arrow-right" size={14}/></button>):<p>No documents found. Try a component name.</p>}</div></div></Dialog>
  </div>;
}
