export type ComponentEntry = { id: string; name: string; group: string; description: string; props: [string, string, string][]; code: string };
const entry = (id: string, name: string, group: string, description: string, code: string, props: [string,string,string][] = []): ComponentEntry => ({ id,name,group,description,code,props });

export const catalog: ComponentEntry[] = [
  entry('button','Button','Inputs','Mechanical clickables for consequential actions. Zero 3D bubbly hover physics or pastel gradients. Just a firm, decisive button built to prevent 3 AM accidental production wipes.', '<Button variant="solid">Deploy to production</Button>\n<Button variant="outline">Inspect telemetry</Button>\n<Button variant="danger">Rollback release</Button>\n<Button variant="ghost">Cancel</Button>', [['variant','solid | outline | danger | ghost | plain | muted','outline'],['size','xs | sm | md | lg','md'],['loading','boolean','false'],['disabled','boolean','false']]),
  entry('input','Input','Inputs','Compact monospace text fields with unambiguous labels and crisp boundaries. Users will actually know what input format you expect before hitting Enter.', '<Field label="NODE HOSTNAME" help="FQDN or internal DNS label.">\n  <Input placeholder="e.g. worker-04.us-east.internal" />\n</Field>\n<Field label="SECRET TOKEN" error="Token expired 42 minutes ago.">\n  <Input defaultValue="tok_live_deadbeef" />\n</Field>', [['state','default | success | warning | error','default'],['disabled','boolean','false'],['readOnly','boolean','false']]),
  entry('select','Select','Inputs','Native selection controls that retain rock-solid keyboard navigation. Because re-inventing the native select dropdown with 800 divs is a crime against humanity.', '<Field label="TARGET REGION" help="Deploy closest to your lowest latency infrastructure.">\n  <Select defaultValue="us-east-1">\n    <option value="us-east-1">US East · N. Virginia</option>\n    <option value="eu-central-1">Europe · Frankfurt</option>\n    <option value="ap-southeast-1">Asia Pacific · Singapore</option>\n  </Select>\n</Field>', [['value','string','—'],['defaultValue','string','—'],['disabled','boolean','false']]),
  entry('checkbox','Checkbox','Inputs','Binary state with sharp architectural corners. Checked means yes, unchecked means no. No vague animations or ambiguous intermediate wobbles.', '<Checkbox label="Bypass staging and deploy directly" />\n<Checkbox label="Send alerts to pager" defaultChecked />\n<Checkbox label="Immutable cluster policy" disabled defaultChecked />', [['label','ReactNode','—'],['checked','boolean','—'],['defaultChecked','boolean','false']]),
  entry('radio','Radio','Inputs','Mutually exclusive options with native arrow-key navigation. Pick one path forward and commit to it.', '<fieldset>\n  <legend>LOG VERBOSITY</legend>\n  <Radio name="log" value="info" label="Standard (Info)" defaultChecked />\n  <Radio name="log" value="debug" label="Verbose (Debug)" />\n  <Radio name="log" value="trace" label="Everything (Dump memory on screen)" />\n</fieldset>', [['name','string','—'],['value','string','—'],['label','ReactNode','—']]),
  entry('switch','Switch','Inputs','Immediate binary toggle with a solid monospace track. Sounds like a satisfying military circuit breaker in your head.', '<Switch label="Autonomous failover" defaultChecked />\n<Switch label="Strict TLS 1.3 verification" defaultChecked />', [['checked','boolean','—'],['onChange','ChangeEventHandler','—'],['disabled','boolean','false']]),
  entry('textarea','Textarea','Inputs','Multi-line monospace field for configuration notes, SQL queries, and apologetic post-mortem incident reports.', '<Field label="INCIDENT POST-MORTEM NOTES">\n  <Textarea rows={4} placeholder="It is not DNS. There is no way it is DNS. It was DNS." />\n</Field>'),
  entry('search-input','SearchInput','Inputs','Dedicated search filter for dense data streams. Fast, responsive, and includes a built-in search icon.', '<SearchInput aria-label="Search servers" placeholder="Search clusters, nodes, IPs…" />'),
  entry('number-input','NumberInput','Inputs','Native numeric control with step boundaries and keyboard arrow support. Keep numbers strictly within sanity bounds.', '<Field label="CONCURRENT WORKERS" help="Recommend 1-16 based on core count.">\n  <NumberInput min={1} max={64} defaultValue={8} />\n</Field>'),
  entry('data-table','DataTable','Data display','The crown jewel of Dossier UI. Dense, sortable, selectable, and keyboard-navigable tables designed to make your product manager sweat.', '<DataTable\n  columns={[\n    { key: "id", header: "NODE ID", sortable: true },\n    { key: "role", header: "ROLE" },\n    { key: "cpu", header: "CPU USAGE", numeric: true, sortable: true },\n    { key: "status", header: "HEALTH" }\n  ]}\n  rows={nodes}\n  numbered\n  selectable\n  pagination\n  pageSize={5}\n/>', [['columns','Column<T>[]','required'],['rows','T[]','required'],['density','compact | default | comfortable','default'],['selectable','boolean','false'],['pagination','boolean','false'],['pageSize','number','10'],['numbered','boolean','false']]),
  entry('metric','Metric','Data display','Numbers with gravity. Tabular numerals guarantee numbers do not twitch or wiggle on screen as metrics tick up.', '<Metric label="COFFEE CONSUMED" value="48.2 L" trend="+14% vs sprint start" />\n<Metric label="DEPLOYMENT LATENCY" value="18ms" tone="success" />', [['label','ReactNode','required'],['value','ReactNode','required'],['tone','Tone','neutral'],['trend','ReactNode','—']]),
  entry('metric-row','MetricRow','Data display','The signature ruled row: label on the left, value on the right, zero unnecessary card wrappers in between.', '<MetricRow label="CLUSTER HEALTH" value="99.99%" tone="success" />\n<MetricRow label="FRIDAY DEPLOYS ATTEMPTED" value="1" tone="danger" description="DANGER ZONE" />', [['label','ReactNode','required'],['value','ReactNode','required'],['description','ReactNode','—'],['tone','Tone','neutral']]),
  entry('status','Status','Data display','Rectangular status tags with explicit text. Color reinforces the state; it never carries meaning alone so on-call devs can actually read it.', '<Status tone="success">Operational</Status>\n<Status tone="warning">Degraded</Status>\n<Status tone="danger">Meltdown</Status>\n<Status tone="info">Syncing</Status>', [['tone','neutral | info | success | warning | danger','neutral']]),
  entry('tag','Tag','Data display','Crisp classification tags for commit hashes, release channels, and security clearance levels.', '<Tag index="01" tone="info">PROD-ALPHA</Tag>\n<Tag variant="technical">SHA-256</Tag>\n<Tag variant="filled">STABLE</Tag>', [['tone','Tone','neutral'],['variant','outline | filled | muted | technical','outline'],['index','string','—']]),
  entry('metadata','Metadata','Data display','Quiet, architectural key-value pills that organize environment, cluster, region, and revision metadata.', '<Metadata items={[\n  { label: "ENV", value: "PRODUCTION" },\n  { label: "REGION", value: "US-EAST-1" },\n  { label: "REV", value: "2.4.1" },\n  { label: "CHAOS", value: "LOW" }\n]} />', [['items','{ label, value }[]','required'],['variant','inline | stacked | distributed','inline']]),
  entry('key-value','KeyValueList','Data display','Structured attributes laid out in clean grids. Ideal for node specifications and hardware telemetry.', '<KeyValueList columns={2} items={[\n  ["PROJECT", "PROJECT-HERMES"],\n  ["SUBSYSTEM", "NEURAL-ENGINE"],\n  ["REGION", "US-EAST-1A"],\n  ["LATENCY", "14ms"]\n]} />', [['items','[string, ReactNode][]','required'],['columns','1 | 2 | 3 | 4','1']]),
  entry('audit-timeline','AuditTimeline','Data display','Chronological event history with timestamps and actors. Perfect for tracing exactly who pushed that untested commit at 4:59 PM.', '<AuditTimeline items={[\n  { timestamp: "16:59:02", title: "GIT COMMIT PUSHED", actor: "alice", description: "Fixed typo in prod" },\n  { timestamp: "16:59:44", title: "PIPELINE FAILED", actor: "ci-bot", tone: "danger" },\n  { timestamp: "17:01:12", title: "ROLLBACK INITIATED", actor: "bob", tone: "success" }\n]} />', [['items','AuditTimelineItem[]','required']]),
  entry('progress','Progress','Data display','Restrained horizontal telemetry gauge for CPU capacity, memory allocation, and sprint burn-down.', '<Progress label="MEMORY USAGE" value={78.4} tone="warning" />', [['value','number','required'],['max','number','100'],['label','string','—'],['tone','Tone','neutral']]),
  entry('document-header','DocumentHeader','Document','The crown header of a technical document. Crisp kicker, heavy monospace rule, primary title, and metadata pill row.', '<DocumentHeader\n  kicker="GLOBAL TELEMETRY // SECTOR 7"\n  title="CORE REACTOR CONTROL PLANE"\n  metadata={[["ENV", "PROD"], ["REGION", "US-EAST-1"], ["UPTIME", "99.98%"]]}\n/>', [['kicker','string','—'],['title','string','required'],['metadata','[string, ReactNode][]','—']]),
  entry('section','Section','Document','Numbered, ruled sections that turn long dashboards and dense reports into instantly scannable documents.', '<Section index="[03]" title="Hardware Telemetry" description="Core temperatures and active thread allocation.">\n  <MetricRow label="CPU CORES ONLINE" value="64 / 64" tone="success" />\n</Section>', [['index','string','—'],['title','string','required'],['variant','plain | ruled | numbered | compact','numbered']]),
  entry('rule','Rule','Document','The visual backbone of Dossier UI. Crisp horizontal dividers with thin, heavy, double, dashed, and dotted variants.', '<Rule label="SECTION 02 // LOGS" />\n<Rule weight="heavy" />\n<Rule variant="dashed" />', [['variant','thin | heavy | double | dashed | dotted','thin'],['weight','thin | heavy','thin'],['label','string','—']]),
  entry('figure','Figure','Document','A proper showcase for technical diagrams and telemetry charts: indexed, bordered, and captioned.', '<Figure index="FIG-01" title="TELEMETRY THROUGHPUT" stats={["1.2M OPS/SEC", "99.9% HEALTH"]} caption="Realtime request throughput over 24-hour cycle.">\n  <YourChartComponent />\n</Figure>', [['index','string','—'],['title','ReactNode','required'],['stats','string[]','—'],['caption','ReactNode','—']]),
  entry('annotation','Annotation','Document','Architectural margin notes that explain subtle details without cluttering the main visualization.', '<Annotation title="INCIDENT NOTE" side="left">\n  Power fluctuation caused by coffee machine on same breaker.\n</Annotation>', [['side','left | right | top | bottom','left'],['title','ReactNode','—']]),
  entry('tabs','Tabs','Navigation','Document-style tabs with instant keyboard switching (arrows, Home, End). No animated sliding pills—just pure document switching.', '<Tabs defaultValue="overview">\n  <Tabs.List aria-label="Console views">\n    <Tabs.Trigger value="overview">Overview</Tabs.Trigger>\n    <Tabs.Trigger value="telemetry">Live Telemetry</Tabs.Trigger>\n    <Tabs.Trigger value="logs">Incident Logs</Tabs.Trigger>\n  </Tabs.List>\n  <Tabs.Content value="overview">System overview here</Tabs.Content>\n  <Tabs.Content value="telemetry">Realtime stats here</Tabs.Content>\n  <Tabs.Content value="logs">Raw log stream here</Tabs.Content>\n</Tabs>', [['defaultValue','string','—'],['value','string','—'],['onValueChange','(value: string) => void','—']]),
  entry('sidebar','Sidebar','Navigation','High-density sidebar navigation for technical consoles. Organize your app into classified dossiers.', '<Sidebar>\n  <NavGroup title="MISSION CONTROL">\n    <NavItem href="#/overview" index="01" active>Control Plane</NavItem>\n    <NavItem href="#/data-table" index="02">Data Grids</NavItem>\n    <NavItem href="#/logs" index="03">Audit Trail</NavItem>\n  </NavGroup>\n</Sidebar>'),
  entry('breadcrumb','Breadcrumb','Navigation','Compact location trail that tells you where you are in the system hierarchy so you never get lost in nested routes.', '<Breadcrumb items={[\n  { label: "Infrastructure", href: "#/" },\n  { label: "Clusters", href: "#/clusters" },\n  { label: "us-east-worker-01" }\n]} />', [['items','{ label, href? }[]','—']]),
  entry('pagination','Pagination','Navigation','Direct, accessible page switcher with clear active boundaries.', '<Pagination page={page} pageCount={10} onPageChange={setPage} />', [['page','number','required'],['pageCount','number','required'],['onPageChange','(page: number) => void','required']]),
  entry('dialog','Dialog','Feedback','Focused modals using the native HTML5 <dialog> element. Esc closes it, focus is trapped, and zero bloatware is installed.', '<Dialog open={open} onOpenChange={setOpen} title="Initiate Cluster Reboot" description="Are you certain? This will disconnect 4,200 active sockets.">\n  <p>Please double-check your current branch before proceeding.</p>\n</Dialog>', [['open','boolean','required'],['onOpenChange','(open: boolean) => void','required'],['title','ReactNode','required'],['footer','ReactNode','—']]),
  entry('drawer','Drawer','Feedback','Slide-out inspection drawer for deep dives. For when you need deeper context without navigating to another URL.', '<Drawer open={open} onOpenChange={setOpen} title="Node Diagnostics">\n  <KeyValueList items={[["NODE", "node-714"], ["STATE", "ONLINE"]]} />\n</Drawer>', [['open','boolean','required'],['side','left | right','right']]),
  entry('toast','Toast','Feedback','Discreet notifications styled like teletype printout slips. Informative, polite, and vanishing automatically.', 'const { toast } = useToast();\n\n<Button onClick={() => toast({\n  title: "Deploy Succeeded",\n  description: "All 18 nodes updated with 0 downtime.",\n  tone: "success"\n})}>Trigger Toast</Button>', [['title','string','required'],['tone','Tone','neutral'],['duration','number','5000']]),
  entry('tooltip','Tooltip','Feedback','Fast, lightweight hover tooltips for when an acronym is so obscure even the author forgot what it means.', '<Tooltip content="Kubernetes Out-Of-Memory termination error">\n  <Tag tone="red">OOMKilled</Tag>\n</Tooltip>', [['content','ReactNode','required'],['side','top | bottom | left | right','top']]),
  entry('callout','Callout','Feedback','Prominent advisories with tone-colored borders. Perfect for "DO NOT TOUCH" warnings and security advisories.', '<Callout tone="warning" title="FRIDAY DEPLOY ADVISORY">\n  Deploying on Friday after 4 PM carries a 99.4% probability of weekend regret.\n</Callout>', [['tone','Tone','info'],['title','ReactNode','—']]),
  entry('empty-state','EmptyState','Feedback','A clean, structured placeholder when a search returns zero results. Prevents the "broken blank screen" panic.', '<EmptyState title="ZERO INCIDENTS FOUND" description="Either everything is working smoothly, or the monitoring agent crashed." action={<Button>Restart Monitor</Button>} />'),
  entry('loading','Loading','Feedback','Subtle rectangular skeletons and clean inline progress indicators for pending network requests.', '<TableSkeleton rows={4} columns={3} />\n<InlineLoader label="Querying database" />'),
  entry('code-block','CodeBlock','Technical','Crisp syntax highlighting with line numbers, code framing, and a working one-click clipboard copy button.', '<CodeBlock language="tsx" filename="MissionControl.tsx" lineNumbers>\n  {`import { Button } from "@vikramaditya1010/react";`}\n</CodeBlock>', [['children','string','required'],['language','string','text'],['lineNumbers','boolean','true'],['wrap','boolean','false'],['copyable','boolean','true']]),
  entry('log-viewer','LogViewer','Technical','High-density console stream with severity tones, line numbers, and readable monospace timestamps.', '<LogViewer entries={[\n  { timestamp: "14:02:01", message: "DNS_RESOLVED", detail: "It was DNS." },\n  { timestamp: "14:02:05", message: "COFFEE_BREWED", level: "success", detail: "450ml fresh" }\n]} />', [['entries','LogEntry[]','required'],['wrap','boolean','false'],['lineNumbers','boolean','true']]),
  entry('json-viewer','JSONViewer','Technical','Inspectable JSON formatting with syntax highlights and line numbers. Turns raw 4MB backend blobs into readable trees.', '<JSONViewer value={{ status: "operational", ping: "12ms", chaosMode: false }} />', [['value','unknown','required']]),
  entry('chart-frame','ChartFrame','Technical','Presentation frame for your visualization library. Bring Recharts, Chart.js, D3, Visx, or raw SVGs.', '<ChartFrame title="DATABASE LATENCY" description="P50, P95, and P99 percentiles">\n  <YourChartComponent />\n</ChartFrame>', [['title','ReactNode','—'],['description','ReactNode','—']]),
];

export const componentGroups = ['Inputs','Data display','Document','Navigation','Feedback','Technical'];

export const generalPages = [
  {id:'overview',name:'Overview',group:'Getting started',description:'A visual language for technical systems.'},
  {id:'installation',name:'Installation',group:'Getting started',description:'Set up the packages in your React application.'},
  {id:'principles',name:'Design principles',group:'Getting started',description:'Why round buttons offended our ancestors.'},
  {id:'tokens',name:'Design tokens',group:'Foundations',description:'The shared variables behind the framework.'},
  {id:'typography',name:'Typography',group:'Foundations',description:'A precise monospace type scale.'},
  {id:'layout',name:'Layout & density',group:'Foundations',description:'Compose responsive, information-dense interfaces.'},
  {id:'components',name:'All components',group:'Components',description:'Browse the complete component collection.'},
  {id:'dashboard',name:'Mission dashboard',group:'Examples',description:'An interactive mission control and telemetry console.'},
  {id:'changelog',name:'Changelog',group:'Resources',description:'The archival record of changes.'},
];

export const allPages = [...generalPages,...catalog];
