import { useState } from 'react';
import { Button, ButtonGroup, Checkbox, Radio, Switch, Field, Input, Textarea, Select, SearchInput, NumberInput, Status, Tag, Metadata, Metric, MetricRow, MetricGroup, DocumentHeader, Section, Rule, Grid, Stack, Inline, Heading, Meta, Body, DataTable, Figure, Annotation, CodeBlock, LogViewer, JSONViewer, KeyValueList, AuditTimeline, Progress, ChartFrame, ChartLegend, EmptyState, TableSkeleton, InlineLoader, Pagination, Tabs, Sidebar, NavGroup, NavItem, Breadcrumb, Dialog, Drawer, Tooltip, Callout, useToast } from '@dossier-ui/react';
import { Icon } from '@dossier-ui/icons';

export const events = Array.from({ length: 100 }, (_, i) => ({
  id: `evt_${String(1048 - i).padStart(6, '0')}`,
  channel: ['SMS', 'EMAIL', 'WHATSAPP', 'PUSH'][i % 4],
  provider: ['SINCH', 'AMAZON SES', 'META', 'FIREBASE'][i % 4],
  status: i % 7 === 2 ? 'FAILED' : i % 9 === 4 ? 'PENDING' : 'DELIVERED',
  latency: [314, 521, 920, 182, 406, 287, 332, 219][i % 8],
}));
export const eventColumns = [
  { key: 'id', header: 'EVENT ID', sortable: true },
  { key: 'channel', header: 'CHANNEL', sortable: true },
  { key: 'provider', header: 'PROVIDER', sortable: true },
  { key: 'status', header: 'STATUS', sortable: true, render: (value: unknown) => <Status tone={value === 'FAILED' ? 'danger' : value === 'PENDING' ? 'warning' : 'success'}>{String(value)}</Status> },
  { key: 'latency', header: 'LATENCY', numeric: true, sortable: true, render: (value: unknown) => `${value}ms` },
];
export const logs = [
  {timestamp: '13:40:22.103', message: 'EVENT_ACCEPTED', detail: 'evt_001048 · gateway', level: 'info' as const},
  {timestamp: '13:40:22.117', message: 'POLICY_MATCH', detail: 'sms.default · rev 17', level: 'neutral' as const},
  {timestamp: '13:40:22.220', message: 'PROVIDER_SENT', detail: 'sinch · ap-south-1', level: 'neutral' as const},
  {timestamp: '13:40:22.482', message: 'DELIVERED', detail: '362ms · 200 OK', level: 'success' as const},
];
export function SampleChart({ small = false }: {small?: boolean}) {
  const bars = [29, 36, 31, 48, 43, 55, 40, 51, 64, 48, 69, 57, 72, 65, 78, 60, 70, 82, 71, 85, 64, 74, 80, 95, 76, 88, 71, 82, 91, 77, 96, 84, 90, 72, 85, 97, 86, 94, 78, 89, 100, 85, 92, 79, 91, 102, 87, 95];
  return <svg className={`sample-chart ${small ? 'sample-chart--small' : ''}`} viewBox="0 0 640 170" role="img" aria-label="Illustrative hourly event throughput, increasing from 290 to 950 events"><g className="chart-grid">{[30,65,100,135].map(y=><line key={y} x1="36" x2="626" y1={y} y2={y} />)}</g><g className="chart-labels"><text x="0" y="34">1K</text><text x="0" y="104">500</text><text x="36" y="160">00:00</text><text x="181" y="160">06:00</text><text x="327" y="160">12:00</text><text x="477" y="160">18:00</text><text x="594" y="160">23:59</text></g><g>{bars.map((h,i)=><rect key={i} x={38+i*12.15} y={135-h} width="6" height={h} fill={i > 37 ? 'var(--dossier-accent-green)' : 'var(--dossier-ink)'} opacity={i > 37 ? .85 : .7} />)}</g><path d="M38 95 L74 87 L110 94 L146 80 L182 83 L218 64 L254 71 L290 52 L326 64 L362 47 L398 55 L434 42 L470 49 L506 35 L542 43 L578 27 L614 34" fill="none" stroke="var(--dossier-accent-red)" strokeWidth="1.5" strokeDasharray="4 4" /></svg>;
}

export function ComponentDemo({ id }: { id: string }) {
  const { toast } = useToast();
  const [open, setOpen] = useState(false);
  const [page, setPage] = useState(1);
  const [progress, setProgress] = useState(68);
  const [query, setQuery] = useState('');
  const [cleared, setCleared] = useState(false);
  const save = () => toast({ title: 'Configuration saved', description: 'Revision 18 is ready for deployment.', tone: 'success' });
  switch(id) {
    case 'button': return <Stack><Inline><Button variant="solid" onClick={save}>Deploy changes <Icon name="arrow-up-right" size={14} /></Button><Button variant="outline" onClick={()=>toast({title:'Review complete',description:'All provider checks passed.',tone:'info'})}>Review configuration</Button><Button variant="ghost" onClick={()=>toast({title:'Action cancelled'})}>Cancel</Button></Inline><Inline><Button variant="danger" onClick={()=>setOpen(true)}>Delete record</Button><Button disabled>Disabled</Button><Button loading>Processing</Button></Inline><Dialog open={open} onOpenChange={setOpen} title="Delete record?" description="This is a component demonstration." footer={<Button variant="danger" onClick={()=>{setOpen(false);toast({title:'Demo record deleted',tone:'success'});}}>Confirm delete</Button>}><p>No production data will be affected.</p></Dialog></Stack>;
    case 'input': return <Grid columns={2}><Field label="TENANT ID" help="Your unique workspace identifier."><Input placeholder="e.g. relay-production" /></Field><Field label="API KEY" error="Enter a valid API key to continue."><Input defaultValue="sk_invalid" /></Field><Field label="READ ONLY"><Input value="R360-SMARTBUY" readOnly /></Field><Field label="DISABLED"><Input value="Not available" disabled /></Field></Grid>;
    case 'select': return <Field label="DEPLOYMENT REGION" help="Choose the region closest to your customers."><Select defaultValue="ap-south-1"><option value="ap-south-1">Asia Pacific · Mumbai</option><option value="eu-west-1">Europe · Ireland</option><option value="us-east-1">US East · Virginia</option></Select></Field>;
    case 'checkbox': return <Stack><Checkbox label="Enable event delivery" defaultChecked /><Checkbox label="Send failure notifications" /><Checkbox label="Managed by administrator" disabled defaultChecked /></Stack>;
    case 'radio': return <fieldset className="demo-fieldset"><legend>DEPLOYMENT ENVIRONMENT</legend><Radio name="environment" value="staging" label="Staging" defaultChecked /><Radio name="environment" value="production" label="Production" /><Radio name="environment" value="archive" label="Archive (unavailable)" disabled /></fieldset>;
    case 'switch': return <Stack><Switch label="Live monitoring" defaultChecked /><Switch label="Verbose logging" /><Switch label="Organization policy" disabled defaultChecked /></Stack>;
    case 'textarea': return <Field label="DEPLOYMENT NOTES" help="Describe the changes included in this revision."><Textarea rows={4} placeholder="Updated retry policy for SMS delivery…" /></Field>;
    case 'search-input': return <Stack><SearchInput aria-label="Search event providers" placeholder="Search providers…" value={query} onChange={e=>setQuery(e.target.value)} /><Meta>{['SINCH','AMAZON SES','META','FIREBASE'].filter(p=>p.toLowerCase().includes(query.toLowerCase())).join(' / ') || 'No providers found'}</Meta></Stack>;
    case 'number-input': return <Field label="RETRY LIMIT" help="Between 0 and 10 attempts."><NumberInput min={0} max={10} defaultValue={3} /></Field>;
    case 'data-table': return <DataTable columns={eventColumns} rows={events} getRowId={r=>r.id} numbered selectable pagination pageSize={5} caption="Recent delivery events" />;
    case 'metric': return <MetricGroup><Metric label="EVENTS PROCESSED" value="12,482" trend="+4.6%" /><Metric label="DELIVERY RATE" value="98.7%" tone="success" /><Metric label="P95 LATENCY" value="420ms" /></MetricGroup>;
    case 'metric-row': return <Stack><MetricRow label="EVENTS PROCESSED" description="LAST 24 HOURS" value="12,482" tone="green" /><MetricRow label="DELIVERY RATE" value="98.7%" /><MetricRow label="FAILED EVENTS" value="164" tone="danger" /></Stack>;
    case 'status': return <Inline><Status tone="success">Delivered</Status><Status tone="warning">Pending</Status><Status tone="danger">Failed</Status><Status tone="info">Queued</Status><Status>Inactive</Status></Inline>;
    case 'tag': return <Inline><Tag index="04">HATCH</Tag><Tag tone="blue" variant="technical">PRODUCTION</Tag><Tag variant="filled">WARDEN</Tag><Tag variant="muted">v0.1.0</Tag><Tag tone="red">FAILED</Tag></Inline>;
    case 'metadata': return <Metadata items={[{label:'PROJECT',value:'RELAY'},{label:'ENV',value:'PROD'},{label:'REGION',value:'AP-SOUTH-1'},{label:'REV',value:'17'}]} />;
    case 'key-value': return <KeyValueList columns={2} items={[["TENANT","SMARTBUY"],["PROVIDER","SINCH"],["CHANNEL","SMS"],["LATENCY","362ms"]]} />;
    case 'audit-timeline': return <AuditTimeline items={[{timestamp:'13:40:22.103',title:'RECEIVED',actor:'gateway',description:'Event accepted and assigned to the delivery queue.'},{timestamp:'13:40:22.117',title:'POLICY MATCHED',actor:'policy-engine',description:'Matched sms.default, revision 17.'},{timestamp:'13:40:22.220',title:'PROVIDER SENT',actor:'sinch'},{timestamp:'13:40:22.482',title:'DELIVERED',tone:'success',description:'Provider confirmed delivery in 362ms.'}]} />;
    case 'progress': return <Stack><Progress value={progress} label="BATCH PROGRESS" tone="success" /><Progress value={94.2} label="DELIVERY RATE" /><ButtonGroup><Button size="sm" disabled={progress===0} onClick={()=>setProgress(p=>Math.max(0,p-10))}>− 10%</Button><Button size="sm" disabled={progress===100} onClick={()=>setProgress(p=>Math.min(100,p+10))}>+ 10%</Button></ButtonGroup></Stack>;
    case 'document-header': return <DocumentHeader kicker="RELAY / EVENT INFRASTRUCTURE" title="EVENT DELIVERY CONTROL PLANE" metadata={[["ENV","PROD"],["REGION","AP-SOUTH-1"],["REV","17"]]} />;
    case 'section': return <Section index="03" title="Provider health" description="Delivery performance across configured providers."><MetricRow label="AVAILABLE PROVIDERS" value="4 / 4" tone="success" /></Section>;
    case 'rule': return <Stack><Rule label="SECTION 03" /><Rule weight="heavy" /><Rule variant="double" /><Rule variant="dashed" /><Rule variant="dotted" /></Stack>;
    case 'figure': return <Figure index="01" title="EVENT DELIVERY" stats={["12,482 EVENTS","24 HOURS"]} caption="Delivery throughput by hour. Dashed line indicates the previous period."><SampleChart /></Figure>;
    case 'annotation': return <Annotation title="RETRY PATH" side="left">Failed delivery attempts return to the policy engine. Exponential backoff applies after the third attempt.</Annotation>;
    case 'tabs': return <Tabs defaultValue="overview"><Tabs.List aria-label="Event details"><Tabs.Trigger value="overview">Overview</Tabs.Trigger><Tabs.Trigger value="events">Events</Tabs.Trigger><Tabs.Trigger value="policies">Policies</Tabs.Trigger><Tabs.Trigger value="archive" disabled>Archive</Tabs.Trigger></Tabs.List><Tabs.Content value="overview"><KeyValueList columns={2} items={[["SYSTEM","RELAY"],["ENVIRONMENT","PRODUCTION"],["REGION","AP-SOUTH-1"],["REVISION","17"]]} /></Tabs.Content><Tabs.Content value="events"><DataTable rows={events.slice(0,3)} columns={eventColumns} /></Tabs.Content><Tabs.Content value="policies"><Callout title="ACTIVE POLICY">Retry up to 3 times using exponential backoff.</Callout></Tabs.Content></Tabs>;
    case 'sidebar': return <div className="sidebar-specimen"><Sidebar><NavGroup title="WORKSPACE"><NavItem href="#/sidebar" index="01" active>Overview</NavItem><NavItem href="#/data-table" index="02">Events</NavItem><NavItem href="#/metadata" index="03">Providers</NavItem><NavItem href="#/audit-timeline" index="04">Audit trail</NavItem></NavGroup></Sidebar><div><Meta>APPLICATION CONTENT</Meta><p>Navigation is a document index.</p></div></div>;
    case 'breadcrumb': return <Breadcrumb items={[{label:'Documentation',href:'#/overview'},{label:'Components',href:'#/components'},{label:'Breadcrumb'}]} />;
    case 'pagination': return <Stack><Meta>PAGE {page} OF 12</Meta><Pagination page={page} pageCount={12} onPageChange={setPage} /></Stack>;
    case 'dialog': return <><Button onClick={()=>setOpen(true)}>Open dialog <Icon name="external" size={14} /></Button><Dialog open={open} onOpenChange={setOpen} title="Review deployment" description="Deploy revision 18 to production." footer={<Inline><Button variant="ghost" onClick={()=>setOpen(false)}>Cancel</Button><Button variant="solid" onClick={()=>{setOpen(false);save();}}>Deploy revision</Button></Inline>}><KeyValueList items={[["ENVIRONMENT","PRODUCTION"],["REGION","AP-SOUTH-1"],["CHECKS","4 / 4 PASSED"]]} /></Dialog></>;
    case 'drawer': return <><Button onClick={()=>setOpen(true)}>Inspect event <Icon name="arrow-right" size={14} /></Button><Drawer open={open} onOpenChange={setOpen} title="Event details" description="Delivery record evt_001048"><Stack><Status tone="success">Delivered</Status><KeyValueList items={[["ID","evt_001048"],["PROVIDER","SINCH"],["LATENCY","314ms"]]} /><ComponentDemo id="audit-timeline" /></Stack></Drawer></>;
    case 'toast': return <Inline><Button onClick={save}>Success notice</Button><Button onClick={()=>toast({title:'Provider unavailable',description:'The delivery will be retried in 30 seconds.',tone:'warning'})}>Warning notice</Button><Button variant="danger" onClick={()=>toast({title:'Delivery failed',description:'Check the provider credentials.',tone:'danger'})}>Error notice</Button></Inline>;
    case 'tooltip': return <Inline><Tooltip content="Copy the event identifier"><Button onClick={()=>toast({title:'Demonstration action',tone:'info'})}>Hover or focus me</Button></Tooltip></Inline>;
    case 'callout': return <Stack><Callout tone="info" title="RETENTION POLICY">Event logs are retained for 30 days.</Callout><Callout tone="warning" title="CERTIFICATE EXPIRING">Rotate provider credentials before 30 September.</Callout><Callout tone="success" title="SYSTEM OPERATIONAL">All four providers are accepting events.</Callout></Stack>;
    case 'empty-state': return cleared ? <DataTable columns={eventColumns} rows={events.slice(0,3)} /> : <EmptyState title="NO EVENTS FOUND" description="No events matched the current filters." action={<Button onClick={()=>setCleared(true)}>Clear filters</Button>} />;
    case 'loading': return <Stack><TableSkeleton rows={4} columns={3} /><InlineLoader label="Loading events" /></Stack>;
    case 'code-block': return <CodeBlock language="tsx" filename="app.tsx" lineNumbers>{'import { Button } from "@dossier-ui/react";\nimport "@dossier-ui/react/styles.css";\n\nexport function App() {\n  return <Button variant="solid">Deploy</Button>;\n}'}</CodeBlock>;
    case 'log-viewer': return <LogViewer entries={logs} lineNumbers />;
    case 'json-viewer': return <JSONViewer value={{event:'evt_001048',status:'delivered',provider:{name:'sinch',region:'ap-south-1'},latency:314,retries:0}} />;
    case 'chart-frame': return <ChartFrame title="EVENT THROUGHPUT" description="Events per hour · last 24 hours"><SampleChart /><ChartLegend items={[{label:'Current period',color:'var(--dossier-ink)'},{label:'Previous period',color:'var(--dossier-accent-red)'}]} /></ChartFrame>;
    default: return <Body>Select a component from the index.</Body>;
  }
}

export function Dashboard() {
  const [query,setQuery] = useState('');
  const [status,setStatus] = useState('all');
  const [open,setOpen] = useState(false);
  const {toast} = useToast();
  const filtered = events.filter(e=>(status==='all'||e.status===status)&&Object.values(e).some(v=>String(v).toLowerCase().includes(query.toLowerCase())));
  return <div className="dashboard"><DocumentHeader kicker="RELAY / EVENT INFRASTRUCTURE" title="EVENT DELIVERY CONTROL PLANE" metadata={[["ENV","PROD"],["TENANT","SMARTBUY"],["REGION","AP-SOUTH-1"],["REV","17"]]} /><div className="dashboard-toolbar"><Status tone="success">All systems operational</Status><Button size="sm" onClick={()=>setOpen(true)}><Icon name="settings" size={14} /> Configure</Button></div><MetricGroup><Metric label="EVENTS PROCESSED" value="12,482" trend="+4.6%" /><Metric label="DELIVERY RATE" value="98.7%" tone="success" /><Metric label="FAILED EVENTS" value="164" tone="danger" /><Metric label="P95 LATENCY" value="420ms" /></MetricGroup><Figure index="01" title="EVENT THROUGHPUT" stats={["24 HOURS","4 PROVIDERS"]} caption="Hourly delivery volume. Dashed line represents the previous period. Sample data."><SampleChart /></Figure><Tabs defaultValue="events"><Tabs.List aria-label="Dashboard sections"><Tabs.Trigger value="events">Recent events</Tabs.Trigger><Tabs.Trigger value="audit">Audit trail</Tabs.Trigger><Tabs.Trigger value="logs">Delivery logs</Tabs.Trigger></Tabs.List><Tabs.Content value="events"><div className="dashboard-filters"><SearchInput aria-label="Filter events" placeholder="Filter events…" value={query} onChange={e=>setQuery(e.target.value)} /><Select aria-label="Filter by status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="DELIVERED">Delivered</option><option value="FAILED">Failed</option><option value="PENDING">Pending</option></Select><Meta>{filtered.length} RECORDS</Meta></div><DataTable columns={eventColumns} rows={filtered} getRowId={e=>e.id} selectable numbered pagination pageSize={5} /></Tabs.Content><Tabs.Content value="audit"><ComponentDemo id="audit-timeline" /></Tabs.Content><Tabs.Content value="logs"><LogViewer entries={logs} /></Tabs.Content></Tabs><Dialog open={open} onOpenChange={setOpen} title="Provider configuration" description="Configure the sample delivery environment." footer={<Button variant="solid" onClick={()=>{setOpen(false);toast({title:'Demo configuration saved',tone:'success'});}}>Save configuration</Button>}><Stack><Field label="PROJECT NAME"><Input defaultValue="Relay production" /></Field><Field label="RETRY LIMIT"><NumberInput min={0} max={10} defaultValue={3} /></Field><Switch label="Enable delivery notifications" defaultChecked /></Stack></Dialog></div>;
}

export function LayoutExample() { return <Stack><Grid columns={12}><Grid.Item span={8}><div className="layout-cell">MAIN / 8 COLS</div></Grid.Item><Grid.Item span={4}><div className="layout-cell">ASIDE / 4 COLS</div></Grid.Item></Grid><Grid columns={3}>{['01','02','03'].map(n=><div className="layout-cell" key={n}>{n} / EQUAL WIDTH</div>)}</Grid><Inline><Tag>COMPACT</Tag><Tag>DEFAULT</Tag><Tag>COMFORTABLE</Tag></Inline></Stack>; }
export function TypographyExample() { return <div className="type-specimen"><div><Meta>DISPLAY / 32</Meta><Heading>ENGINEERED FOR CLARITY.</Heading></div><div><Meta>HEADING / 26</Meta><h2>Information has a structure.</h2></div><div><Meta>BODY / 14</Meta><Body>Every line, label, and number earns its place.</Body></div><div><Meta>METADATA / 11</Meta><Meta>PROJECT RELAY / PROD / AP-SOUTH-1 / REV 03</Meta></div><div><Meta>NUMBERS / TABULAR</Meta><span className="type-numerals">0123456789 — 98.7%</span></div></div>; }
